services:
  - type: web
    name: genshin-shop-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://genshin-shop-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free

  - type: web
    name: genshin-shop-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://shop_ghenshin_db_user:tuan1311@cluster0.8vfcbgu.mongodb.net/genshin-shop?appName=Cluster0
      - key: JWT_SECRET
        value: genshin-shop-jwt-secret-2024
    healthCheckPath: /api/health
    plan: free
